name: Deploy DEV

on:
  workflow_dispatch

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install ssh key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.SSH_DEV_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          
      - name: Generate auth hosts
        run: ssh-keyscan -p ${{ secrets.DEV_SERVER_PORT }} ${{ secrets.DEV_SERVER_HOST }} >> ~/.ssh/known_hosts

      # Deploy
      - run: rsync -e 'ssh -p ${{ secrets.DEV_SERVER_PORT }}' --archive --compress --progress . ${{ secrets.DEV_SERVER_USER }}@${{ secrets.DEV_SERVER_HOST }}:${{ secrets.DEV_SERVER_PATH }}
